version: "3"
networks:
  monitor-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    command: ['--config.file=/monitoring/prometheus.yml']
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/monitoring/
    networks:
      - monitor-net
  blackbox:
    privileged: true
    image: prom/blackbox-exporter
    command: ['--config.file=/config/blackbox.yml']
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    ports:
      - "3000:3000"
    user: '472'
    networks:
      - monitor-net
  custom-rest-api:
    image: custom-rest-api-collector
    build:
      context: .
      dockerfile: rest_custom_collector.dockerfile
    ports:
      - "9099:9099"
    networks:
      - monitor-net
