version: "3"
networks:
  monitor-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    command: ['--config.file=/monitoring/prometheus.yml']
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/monitoring/
    networks:
      - monitor-net
  blackbox:
    privileged: true
    image: prom/blackbox-exporter
    command: ['--config.file=/config/blackbox.yml']
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    ports:
      - "3000:3000"
    user: '472'
    networks:
      - monitor-net
    volumes:
      - grafana-storage:/var/lib/grafana
  custom-rest-api:
#    image: custom-rest-api-collector
    container_name: rest_collector
    build:
      context: .
      dockerfile: rest_custom_collector.dockerfile
    ports:
      - "9099:9099"
    networks:
      - monitor-net
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./prometheus:/prometheus
    command:
      - '--config.file=/prometheus/alertmanager.yml'
    ports:
      - 9093:9093
    networks:
      - monitor-net

volumes:
  grafana-storage:
    driver: local
